#!/bin/sh
#
#usage: <host> <item> <class> user password [-f <filter>] [optional parameters]
# Example zabbix item:
# simple get:
# zbxwmi-get[{HOST.HOST},Name,Win32_ComputerSystem,{$WMIUSER},{$WMIPASSWORD}]
# with filter:
# zbxwmi-get[{HOST.HOST},PercentProcessorTime,Win32_PerfFormattedData_PerfOS_Processor,{$WMIUSER},{$WMIPASSWORD},-f Name='_Total']

# this is a required workaround for a Zabbix Appliance 4.2 (and probably other versions?),
# because external checks are running with $PWD set to /
# if you moved the externalscripts directory - change cd to a proper location
cd /usr/lib/zabbix/externalscripts

# if you need to debug uncomment next line:
#echo ./zbxwmi get $1 $2 $3 --username $4 --password $5 $6 $7 $8 $9 > ./zbxwmi-get.log
./zbxwmi get $1 $2 $3 --username $4 --password $5 $6 $7 $8 $9
